### ISSUE TITLE
catkin_make 

### ISSUE THREAD

**Issue by Ducui6688** [Machine-Jonte/moveit_vive#3]
Hello, your package  is very useful, but I have a problem.When I catkin_make, I report an error below. Do you know why?

error：
In file included from /opt/ros/melodic/include/ros/serialization.h:37:0,
                 from /opt/ros/melodic/include/geometry_msgs/PoseStamped.h:14,
                 from /home/cll-pc/catkin_ws/src/vive_ros/src/vive_pose.h:5,
                 from /home/cll-pc/catkin_ws/src/vive_ros/src/vive_pose.cpp:5:
/opt/ros/melodic/include/ros/message_traits.h: In instantiation of ‘static const char* ros::message_traits::MD5Sum<M>::value(const M&) [with M = float]’:
/opt/ros/melodic/include/ros/message_traits.h:254:102:   required from ‘const char* ros::message_traits::md5sum(const M&) [with M = float]’
/opt/ros/melodic/include/ros/publisher.h:116:38:   required from ‘void ros::Publisher::publish(const M&) const [with M = float]’
/home/cll-pc/catkin_ws/src/vive_ros/src/vive_pose.cpp:209:97:   required from here
/opt/ros/melodic/include/ros/message_traits.h:125:14: error: request for member ‘__getMD5Sum’ in ‘m’, which is of non-class type ‘const float’
     return m.__getMD5Sum().c_str();
            ~~^~~~~~~~~~~
/opt/ros/melodic/include/ros/message_traits.h: In instantiation of ‘static const char* ros::message_traits::DataType<M>::value(const M&) [with M = float]’:
/opt/ros/melodic/include/ros/message_traits.h:263:104:   required from ‘const char* ros::message_traits::datatype(const M&) [with M = float]’
/opt/ros/melodic/include/ros/publisher.h:118:11:   required from ‘void ros::Publisher::publish(const M&) const [with M = float]’
/home/cll-pc/catkin_ws/src/vive_ros/src/vive_pose.cpp:209:97:   required from here
/opt/ros/melodic/include/ros/message_traits.h:142:14: error: request for member ‘__getDataType’ in ‘m’, which is of non-class type ‘const float’
     return m.__getDataType().c_str();
            ~~^~~~~~~~~~~~~
/opt/ros/melodic/include/ros/message_traits.h: In instantiation of ‘static const char* ros::message_traits::MD5Sum<M>::value(const M&) [with M = int]’:
/opt/ros/melodic/include/ros/message_traits.h:254:102:   required from ‘const char* ros::message_traits::md5sum(const M&) [with M = int]’
/opt/ros/melodic/include/ros/publisher.h:116:38:   required from ‘void ros::Publisher::publish(const M&) const [with M = int]’
/home/cll-pc/catkin_ws/src/vive_ros/src/vive_pose.cpp:210:91:   required from here
/opt/ros/melodic/include/ros/message_traits.h:125:14: error: request for member ‘__getMD5Sum’ in ‘m’, which is of non-class type ‘const int’
     return m.__getMD5Sum().c_str();
            ~~^~~~~~~~~~~
/opt/ros/melodic/include/ros/message_traits.h: In instantiation of ‘static const char* ros::message_traits::DataType<M>::value(const M&) [with M = int]’:
/opt/ros/melodic/include/ros/message_traits.h:263:104:   required from ‘const char* ros::message_traits::datatype(const M&) [with M = int]’
/opt/ros/melodic/include/ros/publisher.h:118:11:   required from ‘void ros::Publisher::publish(const M&) const [with M = int]’
/home/cll-pc/catkin_ws/src/vive_ros/src/vive_pose.cpp:210:91:   required from here
/opt/ros/melodic/include/ros/message_traits.h:142:14: error: request for member ‘__getDataType’ in ‘m’, which is of non-class type ‘const int’
     return m.__getDataType().c_str();

Sorry to trouble you, but I really can't solve it

**Comment by Machine-Jonte** [comment]
You got it working?

**Comment by Ducui6688** [comment]
Yes, I modified part of the code, and now it can be used. Thank you very much for your reply



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Jonathan ***@***.***&gt;; 
发送时间: 2021年6月7日(星期一) 晚上7:51
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; "State ***@***.***&gt;; 
主题: Re: [Machine-Jonte/moveit_vive] catkin_make  (#3)





 
You got it working?
